version: 2.1
orbs:
  node: circleci/node@4.1.0
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build-deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          install-yarn: true
      - eb/setup
      - checkout
      # install dependencies
      - run:
          name: Install Dependecies
          command: |
            npm install
      # build app
      - run:
          name: Build
          command: |
            npm run build
      # deploy with AWS Elastic Beanstalk
      - run:
          name: Deploy
          command: |
            eb init udagram-api -r $AWS_DEFAULT_REGION -p node.js
            eb deploy Udagramapi-env -l app-<<pipeline.number>>
workflows:
  build-deploy-workflow:
    jobs:
      - build-deploy
