version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@2.0.3
jobs:
  build-deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          install-yarn: true
      - aws-cli/setup
      - checkout
      # install dependencies
      - run:
          name: Install dependecies
          command: |
            npm install
      # build the frontend
      - run:
          name: Build front-end
          command: |
            npm run build
      # deploy to AWS S3 via deploy.sh
      - run:
          name: Deploy
          command: |
            npm run deploy
workflows:
  frontend-build-deploy-workflow:
    jobs:
      - build-deploy
